name: Deploy to Docker Hub

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v', e.g., v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t katistix/pinflow-orbit:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag katistix/pinflow-orbit:latest katistix/pinflow-orbit:$GITHUB_REF_NAME
          docker push katistix/pinflow-orbit --all-tags
